title : Emilio Pisanty
description: 'Quantum physicist'

collections: 
  publications:
    output: true
    permalink: /publications/:path
  front-page-cards:
    output: false

defaults:
  - scope:
      path: ""
      type: "publications"
    values:
      layout: publication-landing-page

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
plugins_dir: [jekyll-gist]
permalink: /:year/:month/:title.html
